const fs = require('fs');
const path = require('path');
process.chdir(__dirname);
const data=JSON.parse(fs.readFileSync('content.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const header=`<header><div class="header-inner"><a class="wordmark" href="/">こってり開発部<span class="wordmark-dot">.</span></a><nav aria-label="主なリンク"><a href="/#apps">アプリ</a><a href="/stories.html">読み物</a><a href="/guides.html">使い方</a></nav></div></header>`;
const footer=`<footer><span>© こってり開発部</span><div><a href="/stories.html">読み物</a><a href="/guides.html">使い方</a><a href="/operator.html">運営者情報</a><a href="/updates.html">お知らせ</a><a href="/privacy.html">プライバシーポリシー</a></div></footer>`;
const page=(slug,title,description,body,type='website')=>`<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="google-adsense-account" content="ca-pub-4960959858706803"><meta name="theme-color" content="#f7f0e3"><title>${esc(title)} | こってり開発部</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://kotteri-apps.com/${slug}.html"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://kotteri-apps.com/${slug}.html"><meta property="og:image" content="https://kotteri-apps.com/og.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header}<main>${body}</main>${footer}</body></html>\n`;
const link=(a,n='')=>`<a class="story-item" href="/${a.slug}.html"><span class="story-num">${n||'↗'}</span><span class="story-copy"><span class="story-type">${esc(a.category)}${a.date?' · '+esc(a.date):''}</span><strong>${esc(a.title)}</strong><span>${esc(a.summary)}</span></span><span class="story-arrow" aria-hidden="true">→</span></a>`;
const glass=`<svg viewBox="0 0 48 48" width="40" height="40" fill="none" aria-hidden="true"><path d="M8 8h32L24 28 8 8Zm16 20v12m-9 0h18M13 14h22" stroke="currentColor" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/></svg>`;
const cup=`<svg viewBox="0 0 48 48" width="40" height="40" fill="none" aria-hidden="true"><path d="M8 15h25v12a12 12 0 0 1-25 0V15Zm25 3h3a6 6 0 0 1 0 12h-3M7 41h30M16 5v4m10-4v4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`;
const app=(kind)=>{const bar=kind==='bar',name=bar?'BAR LOG':'COFFEE LOG';return `<article class="product-card ${kind}-card" aria-labelledby="${kind}-title"><div class="product-visual"><div class="product-caption">${bar?glass:cup}<span>${bar?'FIND YOUR COCKTAIL':'YOUR COFFEE JOURNEY'}</span><strong>${bar?'今夜の一杯から、<br>好みが広がる。':'一杯ずつ、<br>世界が広がる。'}</strong></div><img src="/${kind}-screen.png" width="375" height="590" alt="${bar?'BAR LOGの今日の一杯の画面':'COFFEE LOGの産地パスポートの画面'}" loading="lazy"></div><div class="product-body"><p class="availability">公開中 <span>WEB APP</span></p><h3 id="${kind}-title">${name}</h3><p class="product-description">${bar?'気分から今夜の一杯を探して、飲んだカクテルを記録。好みを見つけながら、マップやテーマ別コレクションを埋めていくアプリ。':'飲んだ豆の産地を、パスポートに。豆やドリンクの好みを残し、世界地図を眺めながら、次の一杯を見つけるアプリ。'}</p><ul class="feature-tags">${(bar?['気分から探す','飲んだ記録','12のコレクション']:['豆とドリンクを記録','産地パスポート','好みを発見']).map(s=>`<li>${s}</li>`).join('')}</ul>${bar?'<p class="age-note">20歳以上の方を対象としたアプリです</p>':''}<div class="product-actions"><a class="button button-primary" href="https://${kind}.kotteri-apps.com/">${name}を開く <span aria-hidden="true">↗</span></a><a class="guide-link" href="/${bar?'bar-log-guide':'coffee-log-guide'}.html">使い方を見る <span aria-hidden="true">→</span></a></div></div></article>`;};
for(const a of data.articles){if(!/^[a-z0-9-]+$/.test(a.slug)||!a.sections?.length)throw Error('Invalid article');const body=`<div class="article-hero"><p class="eyebrow">${esc(a.category)} / BAR LOG</p><h1>${esc(a.title)}</h1><p class="lead">${esc(a.summary)}</p><p class="article-date">公開 <time datetime="${a.date}">${a.date}</time> · こってり開発部</p></div><article class="article-body"><figure class="article-figure"><img src="/${a.image}" alt="BAR LOGの今日の一杯の画面" width="375" height="590"><figcaption>BAR LOGの画面。表示内容は更新により変わることがあります。</figcaption></figure>${a.sections.map(([h,p])=>`<h2>${esc(h)}</h2><p>${esc(p)}</p>`).join('\n')}<aside class="reading-note">20歳以上の方を対象としたアプリです。自分のペースでお楽しみください。</aside></article><div class="article-nav"><a href="https://bar.kotteri-apps.com/"><small>アプリへ</small>BAR LOGを開く ↗</a><a href="/bar-log-guide.html"><small>使い方</small>BAR LOGのはじめ方</a><a href="/${data.articles.find(x=>x.slug!==a.slug).slug}.html"><small>あわせて読む</small>${esc(data.articles.find(x=>x.slug!==a.slug).title)}</a><a href="/stories.html">読み物一覧へ →</a></div>`;fs.writeFileSync(a.slug+'.html',page(a.slug,a.title,a.summary,body,'article'));}
fs.writeFileSync('stories.html',page('stories','読み物','こってり開発部の制作の話と、アプリを楽しむヒント。',`<div class="article-hero"><p class="eyebrow">STORIES</p><h1>好きなことの、<br>つづきの話。</h1><p class="lead">作ったきっかけから、一杯の楽しみ方まで。気になる話からどうぞ。</p></div><section class="story-hub"><h2>新しい記事</h2><div class="story-list">${data.articles.map(a=>link(a)).join('')}</div><h2 class="list-heading">作るまでの話</h2><div class="story-list">${data.legacy.map((a,i)=>link(a,String(i+1).padStart(2,'0'))).join('')}</div></section>`));
fs.writeFileSync('guides.html',page('guides','使い方','COFFEE LOGとBAR LOGの使い方。アプリを選んではじめましょう。',`<div class="article-hero"><p class="eyebrow">START HERE</p><h1>はじめの一杯を、<br>ここから。</h1><p class="lead">使いたいアプリを選んで、探す・記録する・振り返る流れを確認できます。</p></div><section class="guide-grid"><a class="guide-card coffee-card" href="/coffee-log-guide.html">${cup}<span class="eyebrow">COFFEE LOG</span><h2>コーヒーの記録と<br>産地パスポート</h2><p>豆やドリンクを探すところから、好みの記録とパスポートまで。</p><strong>使い方を見る →</strong></a><a class="guide-card bar-card" href="/bar-log-guide.html">${glass}<span class="eyebrow">BAR LOG</span><h2>カクテル選びと<br>コレクション</h2><p>気分から選び、飲みたい一杯を残し、飲んだ記録を振り返る。</p><strong>使い方を見る →</strong><small>20歳以上の方を対象としたアプリです</small></a></section><aside class="account-note"><strong>二つのアプリを使う方へ</strong><p>COFFEE LOGとBAR LOGは同じアカウントで利用できます。ログインはアプリごとに必要で、記録はそれぞれ別々に保存されます。</p></aside>`));
const steps=[['気分から探す','ホームの「気分で探す」から、今の気分に合わせて候補を探せます。名前から調べたい場合は「カクテルを探す」を開いてください。'],['気になる一杯の詳細を見る','候補を選んで、ベースのお酒や味わいなどを確認します。今すぐ飲む予定がなければ、「飲みたい一杯」に残して、次の機会の参考にできます。'],['飲んだカクテルを記録する','実際に飲んだら記録を残します。自分の好みを振り返るための記録なので、気に入った一杯も、そうでなかった一杯も手がかりになります。'],['マップとコレクションを見る','「集める」では、MAPとコレクションを切り替えられます。飲んだ記録は自動で反映され、同じカクテルは何度記録しても1種類として数えます。'],['アカウントについて確認する','COFFEE LOGと同じメールアドレス・パスワードで利用できます。自動でログインが共有される仕組みではないため、BAR LOGでもログインしてください。各アプリの記録は別々に保存されます。']];
fs.writeFileSync('bar-log-guide.html',page('bar-log-guide','BAR LOGのはじめ方','気分で探す、飲みたい一杯を残す、飲んだ記録とコレクションを楽しむ。',`<div class="article-hero"><p class="eyebrow">HOW TO USE / BAR LOG</p><h1>BAR LOGの<br>はじめ方。</h1><p class="lead">探す、残す、振り返る。自分のペースで、好きな一杯を見つけましょう。</p><p class="article-date">更新 2026-10-02</p></div><article class="article-body"><figure class="article-figure"><img src="/bar-screen.png" width="375" height="590" alt="BAR LOGのホーム画面"><figcaption>ホームの「今日の一杯」。候補は表示時に変わります。</figcaption></figure>${steps.map(([h,p],i)=>`<div class="guide-step"><h2>${i+1}. ${h}</h2><p>${p}</p></div>`).join('')}<aside class="reading-note">20歳以上の方を対象としたアプリです。コレクションに期限はありません。短い期間でそろえる必要はなく、飲まない日があっても大丈夫です。</aside></article><div class="article-nav"><a href="https://bar.kotteri-apps.com/">BAR LOGを開く ↗</a><a href="/bar-log-collections.html">12のテーマから、気になるカクテルを見つける →</a><a href="/guides.html">使い方の一覧へ →</a></div>`));
let home=fs.readFileSync('index.html','utf8').replace(/<style>[\s\S]*?<\/style>/,'');
home=home.replace(/<section class="app-section"[\s\S]*?(?=<section class="stories-section")/,`<section class="app-section" id="apps"><div class="section-kicker"><span>01 / APPS</span><span>いま使えるもの</span></div><div class="section-title"><h2><span>今日の一杯を、</span><span>次の楽しみに。</span></h2><p>コーヒーも、カクテルも。<br>好みを残して、次の一杯を見つける。<br>日々の楽しみに寄り添う二つのアプリです。</p></div><div class="products">${app('coffee')}${app('bar')}</div><aside class="account-note"><strong>COFFEE LOGと同じアカウントで利用できます</strong><p>BAR LOGでも同じメールアドレス・パスワードを使えます。ログインはアプリごとに必要で、記録はそれぞれ別々に保存されます。</p></aside><p class="screen-note">掲載画像はアプリの画面です。表示内容は更新により変わることがあります。</p></section>\n`);
home=home.replace(/<section class="stories-section"[\s\S]*?(?=<section class="about")/,`<section class="stories-section" id="stories"><div class="section-kicker"><span>02 / STORIES</span><span>読み物</span></div><div class="section-title"><h2><span>好きなことの、</span><span>つづきの話。</span></h2><p>作ったきっかけも、使う楽しみも。<br>気になる話から、どうぞ。</p></div><div class="featured-story"><div class="story-art">${glass}<span>NEW STORY</span><strong>今夜、何を飲もう。</strong></div><div><p class="eyebrow">新しい記事 · ${data.articles[0].date}</p><h3><a href="/${data.articles[0].slug}.html">${esc(data.articles[0].title)}</a></h3><p>${esc(data.articles[0].summary)}</p><a class="text-link" href="/${data.articles[0].slug}.html">記事を読む →</a></div></div><p class="recommend-label">はじめての方に、おすすめの2本</p><div class="story-list">${[data.legacy[0],data.legacy[3]].map(a=>link(a)).join('')}</div><a class="more-link" href="/stories.html">読み物をすべて見る →</a></section>\n`);
home=home.replace(/<aside class="latest-news"[\s\S]*?<\/aside>/,'');
home=home.replace('</section>\n<section class="app-section"','</section>\n<aside class="latest-news"><span>NEWS</span><time datetime="2026-10-01">2026.10.01</time><a href="/bar-log-launch.html">BAR LOGを公開しました <span aria-hidden="true">→</span></a><a class="all-news" href="/updates.html">お知らせ一覧</a></aside>\n<section class="app-section"');
home=home.replace('開発の話を読む','読み物を読む');fs.writeFileSync('index.html',home);
let updates=fs.readFileSync('updates.html','utf8').replaceAll('こってり開発部とCOFFEE LOGの更新情報です。','こってり開発部、COFFEE LOG、BAR LOGの更新情報です。');
if(!updates.includes('data-update="bar-launch"'))updates=updates.replace('<article class="article-body">','<article class="article-body">\n<div class="update-item" data-update="bar-launch"><time datetime="2026-10-01">2026-10-01</time><p>BAR LOGを公開しました。気分からカクテルを探し、飲んだ記録やマップ、12種類のテーマ別コレクションを楽しめます。<a href="/bar-log-launch.html">紹介記事を読む →</a></p></div>');fs.writeFileSync('updates.html',updates);
for(const file of fs.readdirSync('.').filter(f=>f.endsWith('.html'))){let s=fs.readFileSync(file,'utf8');s=s.replace(/<header>[\s\S]*?<\/header>/,header).replace(/<footer>[\s\S]*?<\/footer>/,footer);if(!s.includes('href="/refresh.css"'))s=s.replace('</head>','<link rel="stylesheet" href="/refresh.css">\n</head>');fs.writeFileSync(file,s);}
const pages=fs.readdirSync('.').filter(f=>f.endsWith('.html')).sort();fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+pages.map(f=>`  <url><loc>https://kotteri-apps.com/${f==='index.html'?'':f}</loc></url>`).join('\n')+'\n</urlset>\n');
console.log('Built articles, guides, homepage, navigation and sitemap.');
